FROM node:22-bookworm-slim AS build

ENV PNPM_HOME=/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN corepack enable
WORKDIR /app

COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @igreja/api build

ENV NODE_ENV=production
CMD ["pnpm", "--filter", "@igreja/api", "whatsapp:worker:start"]
