import { PERMISSIONS, type AuthenticatedPrincipal, type Permission } from '../../domain/entities/permission';
import { FollowupNoteContent, FollowupStageDefinition, FollowupTagDefinition, normalizeNextAction, type FollowupNoteVisibility } from '../../domain/entities/pastoral-followup';
import type { PastoralFollowupRepository } from '../ports/pastoral-followup.port';
import { AuthorizationError, NotFoundError } from './errors';

function requirePermission(principal: AuthenticatedPrincipal, permission: Permission) {
  if (!principal.permissions.includes(permission)) throw new AuthorizationError('Você não tem permissão para realizar esta ação.');
}
function requireRead(principal: AuthenticatedPrincipal) {
  if (!principal.permissions.includes(PERMISSIONS.followupsReadOwn) && !principal.permissions.includes(PERMISSIONS.followupsReadAll)) throw new AuthorizationError('Você não tem acesso aos acompanhamentos.');
}

export class ListFollowupBoardUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} execute(principal: AuthenticatedPrincipal) { requireRead(principal); return this.repository.board(principal); } }
export class GetFollowupUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} async execute(principal: AuthenticatedPrincipal, id: string) { requireRead(principal); const item = await this.repository.detail(principal, id); if (!item) throw new NotFoundError('Acompanhamento não encontrado ou sem acesso.'); return item; } }
export class CreateFollowupFromConversationUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} async execute(principal: AuthenticatedPrincipal, conversationId: string) { requirePermission(principal, PERMISSIONS.followupsManage); const item = await this.repository.createFromConversation(principal, conversationId); if (!item) throw new NotFoundError('Conversa não encontrada ou sem acesso.'); return item; } }
export class MoveFollowupUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} async execute(principal: AuthenticatedPrincipal, id: string, stageId: string) { requirePermission(principal, PERMISSIONS.followupsManage); const item = await this.repository.move(principal, id, stageId); if (!item) throw new NotFoundError('Acompanhamento ou etapa não encontrado.'); return item; } }
export class UpdateFollowupUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} async execute(principal: AuthenticatedPrincipal, id: string, input: { nextActionAt?: string | null; tagIds: string[] }) { requirePermission(principal, PERMISSIONS.followupsManage); const item = await this.repository.update(principal, id, { nextActionAt: normalizeNextAction(input.nextActionAt), tagIds: [...new Set(input.tagIds)] }); if (!item) throw new NotFoundError('Acompanhamento ou etiqueta não encontrado.'); return item; } }
export class ListFollowupStagesUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} execute(principal: AuthenticatedPrincipal) { requireRead(principal); return this.repository.stages(principal); } }
export class CreateFollowupStageUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} execute(principal: AuthenticatedPrincipal, input: { name: string; color: string }) { requirePermission(principal, PERMISSIONS.followupsPipelineManage); return this.repository.createStage(principal, FollowupStageDefinition.create(input)); } }
export class ListFollowupTagsUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} execute(principal: AuthenticatedPrincipal) { requireRead(principal); return this.repository.tags(principal); } }
export class CreateFollowupTagUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} execute(principal: AuthenticatedPrincipal, input: { name: string; color: string }) { requirePermission(principal, PERMISSIONS.followupsPipelineManage); return this.repository.createTag(principal, FollowupTagDefinition.create(input)); } }
export class AddFollowupNoteUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} async execute(principal: AuthenticatedPrincipal, id: string, input: { body: string; visibility: FollowupNoteVisibility }) { requirePermission(principal, PERMISSIONS.followupsNotesManage); const note = await this.repository.addNote(principal, id, FollowupNoteContent.create(input)); if (!note) throw new NotFoundError('Acompanhamento não encontrado ou sem acesso.'); return note; } }
export class RemoveFollowupNoteUseCase { constructor(private readonly repository: PastoralFollowupRepository) {} async execute(principal: AuthenticatedPrincipal, id: string, noteId: string) { requirePermission(principal, PERMISSIONS.followupsNotesManage); const removed = await this.repository.removeNote(principal, id, noteId); if (!removed) throw new NotFoundError('Anotação não encontrada ou sem acesso.'); return { removed: true }; } }
